### ISSUE TITLE
Add username and password for Transmission GUI to bookmarklet

### ISSUE THREAD

**Issue by saltedlolly** [bulljit/Transmission-Add-Torrent-Bookmarkelet#6]
I was thinking about the username / password for accessing the webui. When it is enabled in Transmission, you need to enter the username and password when you ever you load the bookmarklet which some users might find annoying after a while. What are your thoughts on the idea of modifying the form in installbmlet.html to optionally include the username and password in the bookmarklet. Is that very insecure? What do you think?

Something like:

[_] *Skip Transmission login? (Optional)

Username: [__________]
Password:  [__________]

*If you have included a username and password for accessing the Transmission Web UI, you will need to enter them every time you use the Bookmarklet. You can optionally avoid this by checking the box above and entering your username and password. This will bypass the password prompt.

**Comment by bulljit** [comment]
Though I wouldn't advise it, you should be able to pass the info as user:pass@ip:port

But on my iPhone and MacBook, I only have to enter this info once, and then it seems to persist (guessing it's being set by a cookie or in the cache).  I assume it will expire at some time and I will have to reenter the info.  However, I accept slight inconvenience rather than sending my user:pass in a url and worst yet available to anyone that has access to my bookmarks.

Is it not behaving similarly for you?

**Comment by saltedlolly** [comment]
Notes for how to do this are in the readme so I will close this.
